# Generated by Django 4.2.6 on 2023-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Total_Deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Total_Income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
